<?xml version="1.0" encoding="utf-8"?><Database Name="Storage" Class="StorageDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GJY-PC\SQLEXPRESS;Initial Catalog=Storage;Integrated Security=True;Pooling=False" SettingsObjectName="Storage.Properties.Settings" SettingsPropertyName="StorageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Batch" Member="Batch">
    <Type Name="Batch">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="InOut" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Batch_CurrentPort" Member="CurrentPort" ThisKey="ID" OtherKey="BatchID" Type="CurrentPort" />
      <Association Name="Batch_Export" Member="Export" ThisKey="ID" OtherKey="BatchID" Type="Export" />
      <Association Name="Batch_Import" Member="Import" ThisKey="ID" OtherKey="BatchID" Type="Import" />
      <Association Name="Contact_Batch" Member="Contact" ThisKey="ID" OtherKey="ID" Type="Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pit" Member="Pit">
    <Type Name="Pit">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Pit_CurrentPort" Member="CurrentPort" ThisKey="ID" OtherKey="PitID" Type="CurrentPort" />
      <Association Name="Pit_Export" Member="Export" ThisKey="ID" OtherKey="PitID" Type="Export" />
      <Association Name="Pit_Import" Member="Import" ThisKey="ID" OtherKey="PitID" Type="Import" />
    </Type>
  </Table>
  <Table Name="dbo.Contact" Member="Contact">
    <Type Name="Contact">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="[Identity]" Member="Identity" Type="System.String" DbType="NChar(18)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Contact_Batch" Member="Batch" ThisKey="ID" OtherKey="ID" Type="Batch" Cardinality="One" />
      <Association Name="Contact_CurrentPort" Member="CurrentPort" ThisKey="ID" OtherKey="ContactID" Type="CurrentPort" />
      <Association Name="Contact_Export" Member="Export" ThisKey="ID" OtherKey="ContactID" Type="Export" />
      <Association Name="Contact_Import" Member="Import" ThisKey="ID" OtherKey="ContactID" Type="Import" />
    </Type>
  </Table>
  <Table Name="dbo.CurrentPort" Member="CurrentPort">
    <Type Name="CurrentPort">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContactID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KindID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Batch_CurrentPort" Member="Batch" ThisKey="BatchID" OtherKey="ID" Type="Batch" IsForeignKey="true" />
      <Association Name="Contact_CurrentPort" Member="Contact" ThisKey="ContactID" OtherKey="ID" Type="Contact" IsForeignKey="true" />
      <Association Name="Pit_CurrentPort" Member="Pit" ThisKey="PitID" OtherKey="ID" Type="Pit" IsForeignKey="true" />
      <Association Name="Kind_CurrentPort" Member="Kind" ThisKey="KindID" OtherKey="ID" Type="Kind" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Export" Member="Export">
    <Type Name="Export">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContactID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KindID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Batch_Export" Member="Batch" ThisKey="BatchID" OtherKey="ID" Type="Batch" IsForeignKey="true" />
      <Association Name="Contact_Export" Member="Contact" ThisKey="ContactID" OtherKey="ID" Type="Contact" IsForeignKey="true" />
      <Association Name="Pit_Export" Member="Pit" ThisKey="PitID" OtherKey="ID" Type="Pit" IsForeignKey="true" />
      <Association Name="Kind_Export" Member="Kind" ThisKey="KindID" OtherKey="ID" Type="Kind" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Import" Member="Import">
    <Type Name="Import">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContactID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KindID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Batch_Import" Member="Batch" ThisKey="BatchID" OtherKey="ID" Type="Batch" IsForeignKey="true" />
      <Association Name="Contact_Import" Member="Contact" ThisKey="ContactID" OtherKey="ID" Type="Contact" IsForeignKey="true" />
      <Association Name="Pit_Import" Member="Pit" ThisKey="PitID" OtherKey="ID" Type="Pit" IsForeignKey="true" />
      <Association Name="Kind_Import" Member="Kind" ThisKey="KindID" OtherKey="ID" Type="Kind" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kind" Member="Kind">
    <Type Name="Kind">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Kind_CurrentPort" Member="CurrentPort" ThisKey="ID" OtherKey="KindID" Type="CurrentPort" />
      <Association Name="Kind_Export" Member="Export" ThisKey="ID" OtherKey="KindID" Type="Export" />
      <Association Name="Kind_Import" Member="Import" ThisKey="ID" OtherKey="KindID" Type="Import" />
    </Type>
  </Table>
</Database>